server:
  port: 8085

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/polls_app
    username: root
    password: sunIl!098
    initialization-mode: ALWAYS
    dbcp2:
      validation-query: SELECT 1
      test-while-idle: true